// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#include "TrafficLightSM.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset

// Zeitvariable (einfacher Zähler, wird bei jedem TICK erhöht)
static int time = 0;

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(TrafficLightSM* sm, TrafficLightSM_StateId desired_state);

static void ROOT_enter(TrafficLightSM* sm);

static void INIT_enter(TrafficLightSM* sm);

static void INIT_exit(TrafficLightSM* sm);

static void INIT_do(TrafficLightSM* sm);

static void TRAFFICLIGHTGREEN_enter(TrafficLightSM* sm);

static void TRAFFICLIGHTGREEN_exit(TrafficLightSM* sm);

static void TRAFFICLIGHTGREEN_tick(TrafficLightSM* sm);

static void TRAFFICLIGHTSTATERED_enter(TrafficLightSM* sm);

static void TRAFFICLIGHTSTATERED_exit(TrafficLightSM* sm);

static void TRAFFICLIGHTSTATERED_requestgreen(TrafficLightSM* sm);

static void TRAFFICLIGHTSTATERED_tick(TrafficLightSM* sm);

static void TRAFFICLIGHTSTATEREDYELLOW_enter(TrafficLightSM* sm);

static void TRAFFICLIGHTSTATEREDYELLOW_exit(TrafficLightSM* sm);

static void TRAFFICLIGHTSTATEREDYELLOW_tick(TrafficLightSM* sm);

static void TRAFFICLIGHTYELLOW_enter(TrafficLightSM* sm);

static void TRAFFICLIGHTYELLOW_exit(TrafficLightSM* sm);

static void TRAFFICLIGHTYELLOW_tick(TrafficLightSM* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void TrafficLightSM_ctor(TrafficLightSM* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void TrafficLightSM_start(TrafficLightSM* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(Init)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `Init`.
            INIT_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void TrafficLightSM_dispatch_event(TrafficLightSM* sm, TrafficLightSM_EventId event_id)
{
    switch (sm->state_id)
    {
        // STATE: TrafficLightSM
        case TrafficLightSM_StateId_ROOT:
            // No events handled by this state (or its ancestors).
            break;
        
        // STATE: Init
        case TrafficLightSM_StateId_INIT:
            switch (event_id)
            {
                case TrafficLightSM_EventId_DO: INIT_do(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: TrafficLightGreen
        case TrafficLightSM_StateId_TRAFFICLIGHTGREEN:
            switch (event_id)
            {
                case TrafficLightSM_EventId_TICK: TRAFFICLIGHTGREEN_tick(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: TrafficLightStateRed
        case TrafficLightSM_StateId_TRAFFICLIGHTSTATERED:
            switch (event_id)
            {
                case TrafficLightSM_EventId_TICK: TRAFFICLIGHTSTATERED_tick(sm); break;
                case TrafficLightSM_EventId_REQUESTGREEN: TRAFFICLIGHTSTATERED_requestgreen(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: TrafficLightStateRedYellow
        case TrafficLightSM_StateId_TRAFFICLIGHTSTATEREDYELLOW:
            switch (event_id)
            {
                case TrafficLightSM_EventId_TICK: TRAFFICLIGHTSTATEREDYELLOW_tick(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: TrafficLightYellow
        case TrafficLightSM_StateId_TRAFFICLIGHTYELLOW:
            switch (event_id)
            {
                case TrafficLightSM_EventId_TICK: TRAFFICLIGHTYELLOW_tick(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(TrafficLightSM* sm, TrafficLightSM_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case TrafficLightSM_StateId_INIT: INIT_exit(sm); break;
            
            case TrafficLightSM_StateId_TRAFFICLIGHTGREEN: TRAFFICLIGHTGREEN_exit(sm); break;
            
            case TrafficLightSM_StateId_TRAFFICLIGHTSTATERED: TRAFFICLIGHTSTATERED_exit(sm); break;
            
            case TrafficLightSM_StateId_TRAFFICLIGHTSTATEREDYELLOW: TRAFFICLIGHTSTATEREDYELLOW_exit(sm); break;
            
            case TrafficLightSM_StateId_TRAFFICLIGHTYELLOW: TRAFFICLIGHTYELLOW_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(TrafficLightSM* sm)
{
    sm->state_id = TrafficLightSM_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state INIT
////////////////////////////////////////////////////////////////////////////////

static void INIT_enter(TrafficLightSM* sm)
{
    sm->state_id = TrafficLightSM_StateId_INIT;
    
    // Init behavior
    // uml: enter / { initRedLight(); }
    {
        // Step 1: execute action `initRedLight();`
        initRedLight();
    } // end of behavior for Init
    
    // Init behavior
    // uml: enter / { initYellowLight(); }
    {
        // Step 1: execute action `initYellowLight();`
        initYellowLight();
    } // end of behavior for Init
    
    // Init behavior
    // uml: enter / { initGreenLight(); }
    {
        // Step 1: execute action `initGreenLight();`
        initGreenLight();
    } // end of behavior for Init
}

static void INIT_exit(TrafficLightSM* sm)
{
    sm->state_id = TrafficLightSM_StateId_ROOT;
}

static void INIT_do(TrafficLightSM* sm)
{
    // Init behavior
    // uml: do TransitionTo(TrafficLightStateRed)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        INIT_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightStateRed`.
        TRAFFICLIGHTSTATERED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Init
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRAFFICLIGHTGREEN
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTGREEN_enter(TrafficLightSM* sm)
{
    sm->state_id = TrafficLightSM_StateId_TRAFFICLIGHTGREEN;
    
    // TrafficLightGreen behavior
    // uml: enter / { turnOnGreenLight() }
    {
        // Step 1: execute action `turnOnGreenLight()`
        turnOnGreenLight();
    } // end of behavior for TrafficLightGreen
    
    // TrafficLightGreen behavior
    // uml: enter / { time = 0 }
    {
        // Step 1: execute action `time = 0`
        time = 0;
    } // end of behavior for TrafficLightGreen
}

static void TRAFFICLIGHTGREEN_exit(TrafficLightSM* sm)
{
    // TrafficLightGreen behavior
    // uml: exit / { turnOffGreenLight() }
    {
        // Step 1: execute action `turnOffGreenLight()`
        turnOffGreenLight();
    } // end of behavior for TrafficLightGreen
    
    sm->state_id = TrafficLightSM_StateId_ROOT;
}

static void TRAFFICLIGHTGREEN_tick(TrafficLightSM* sm)
{
    // TrafficLightGreen behavior
    // uml: tick / { time++ }
    {
        // Step 1: execute action `time++`
        time++;
    } // end of behavior for TrafficLightGreen
    
    // TrafficLightGreen behavior
    // uml: tick [time > 5000] TransitionTo(TrafficLightYellow)
    if (time > 10000)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTGREEN_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightYellow`.
        TRAFFICLIGHTYELLOW_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightGreen
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRAFFICLIGHTSTATERED
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTSTATERED_enter(TrafficLightSM* sm)
{
    sm->state_id = TrafficLightSM_StateId_TRAFFICLIGHTSTATERED;
    
    // TrafficLightStateRed behavior
    // uml: enter / { turnOnRedLight() }
    {
        // Step 1: execute action `turnOnRedLight()`
        turnOnRedLight();
    } // end of behavior for TrafficLightStateRed
    
    // TrafficLightStateRed behavior
    // uml: enter / { time = 0 }
    {
        // Step 1: execute action `time = 0`
        time = 0;
    } // end of behavior for TrafficLightStateRed
}

static void TRAFFICLIGHTSTATERED_exit(TrafficLightSM* sm)
{
    // TrafficLightStateRed behavior
    // uml: exit / { turnOffRedLight() }
    {
        // Step 1: execute action `turnOffRedLight()`
        turnOffRedLight();
    } // end of behavior for TrafficLightStateRed
    
    sm->state_id = TrafficLightSM_StateId_ROOT;
}

static void TRAFFICLIGHTSTATERED_requestgreen(TrafficLightSM* sm)
{
    // TrafficLightStateRed behavior
    // uml: requestGreen TransitionTo(TrafficLightStateRedYellow)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTSTATERED_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightStateRedYellow`.
        TRAFFICLIGHTSTATEREDYELLOW_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightStateRed
    
    // No ancestor handles this event.
}

static void TRAFFICLIGHTSTATERED_tick(TrafficLightSM* sm)
{
    // TrafficLightStateRed behavior
    // uml: tick / { time++ }
    {
        // Step 1: execute action `time++`
        time++;
    } // end of behavior for TrafficLightStateRed
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRAFFICLIGHTSTATEREDYELLOW
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTSTATEREDYELLOW_enter(TrafficLightSM* sm)
{
    sm->state_id = TrafficLightSM_StateId_TRAFFICLIGHTSTATEREDYELLOW;
    
    // TrafficLightStateRedYellow behavior
    // uml: enter / { turnOnRedLight() }
    {
        // Step 1: execute action `turnOnRedLight()`
        turnOnRedLight();
    } // end of behavior for TrafficLightStateRedYellow
    
    // TrafficLightStateRedYellow behavior
    // uml: enter / { turnOnYellowLight() }
    {
        // Step 1: execute action `turnOnYellowLight()`
        turnOnYellowLight();
    } // end of behavior for TrafficLightStateRedYellow
    
    // TrafficLightStateRedYellow behavior
    // uml: enter / { time = 0 }
    {
        // Step 1: execute action `time = 0`
        time = 0;
    } // end of behavior for TrafficLightStateRedYellow
}

static void TRAFFICLIGHTSTATEREDYELLOW_exit(TrafficLightSM* sm)
{
    // TrafficLightStateRedYellow behavior
    // uml: exit / { turnOffRedLight() }
    {
        // Step 1: execute action `turnOffRedLight()`
        turnOffRedLight();
    } // end of behavior for TrafficLightStateRedYellow
    
    // TrafficLightStateRedYellow behavior
    // uml: exit / { turnOffYellowLight() }
    {
        // Step 1: execute action `turnOffYellowLight()`
        turnOffYellowLight();
    } // end of behavior for TrafficLightStateRedYellow
    
    sm->state_id = TrafficLightSM_StateId_ROOT;
}

static void TRAFFICLIGHTSTATEREDYELLOW_tick(TrafficLightSM* sm)
{
    // TrafficLightStateRedYellow behavior
    // uml: tick / { time++ }
    {
        // Step 1: execute action `time++`
        time++;
    } // end of behavior for TrafficLightStateRedYellow
    
    // TrafficLightStateRedYellow behavior
    // uml: tick [time > 2000] TransitionTo(TrafficLightGreen)
    if (time > 2000)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTSTATEREDYELLOW_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightGreen`.
        TRAFFICLIGHTGREEN_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightStateRedYellow
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRAFFICLIGHTYELLOW
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTYELLOW_enter(TrafficLightSM* sm)
{
    sm->state_id = TrafficLightSM_StateId_TRAFFICLIGHTYELLOW;
    
    // TrafficLightYellow behavior
    // uml: enter / { turnOnYellowLight() }
    {
        // Step 1: execute action `turnOnYellowLight()`
        turnOnYellowLight();
    } // end of behavior for TrafficLightYellow
    
    // TrafficLightYellow behavior
    // uml: enter / { time = 0 }
    {
        // Step 1: execute action `time = 0`
        time = 0;
    } // end of behavior for TrafficLightYellow
}

static void TRAFFICLIGHTYELLOW_exit(TrafficLightSM* sm)
{
    // TrafficLightYellow behavior
    // uml: exit / { turnOffYellowLight() }
    {
        // Step 1: execute action `turnOffYellowLight()`
        turnOffYellowLight();
    } // end of behavior for TrafficLightYellow
    
    sm->state_id = TrafficLightSM_StateId_ROOT;
}

static void TRAFFICLIGHTYELLOW_tick(TrafficLightSM* sm)
{
    // TrafficLightYellow behavior
    // uml: tick / { time++ }
    {
        // Step 1: execute action `time++`
        time++;
    } // end of behavior for TrafficLightYellow
    
    // TrafficLightYellow behavior
    // uml: tick [time > 3000] TransitionTo(TrafficLightStateRed)
    if (time > 3000)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTYELLOW_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightStateRed`.
        TRAFFICLIGHTSTATERED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightYellow
    
    // No ancestor handles this event.
}

// Thread safe.
char const * TrafficLightSM_state_id_to_string(TrafficLightSM_StateId id)
{
    switch (id)
    {
        case TrafficLightSM_StateId_ROOT: return "ROOT";
        case TrafficLightSM_StateId_INIT: return "INIT";
        case TrafficLightSM_StateId_TRAFFICLIGHTGREEN: return "TRAFFICLIGHTGREEN";
        case TrafficLightSM_StateId_TRAFFICLIGHTSTATERED: return "TRAFFICLIGHTSTATERED";
        case TrafficLightSM_StateId_TRAFFICLIGHTSTATEREDYELLOW: return "TRAFFICLIGHTSTATEREDYELLOW";
        case TrafficLightSM_StateId_TRAFFICLIGHTYELLOW: return "TRAFFICLIGHTYELLOW";
        default: return "?";
    }
}

// Thread safe.
char const * TrafficLightSM_event_id_to_string(TrafficLightSM_EventId id)
{
    switch (id)
    {
        case TrafficLightSM_EventId_DO: return "DO";
        case TrafficLightSM_EventId_REQUESTGREEN: return "REQUESTGREEN";
        case TrafficLightSM_EventId_TICK: return "TICK";
        default: return "?";
    }
}
