// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#pragma once  // You can also specify normal include guard. See https://github.com/StateSmith/StateSmith/blob/main/docs/settings.md
#include <stdint.h>

typedef enum TrafficLightSM_EventId
{
    TrafficLightSM_EventId_DO = 0, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
    TrafficLightSM_EventId_REQUESTGREEN = 1,
    TrafficLightSM_EventId_TICK = 2
} TrafficLightSM_EventId;

enum
{
    TrafficLightSM_EventIdCount = 3
};

typedef enum TrafficLightSM_StateId
{
    TrafficLightSM_StateId_ROOT = 0,
    TrafficLightSM_StateId_INIT = 1,
    TrafficLightSM_StateId_TRAFFICLIGHTGREEN = 2,
    TrafficLightSM_StateId_TRAFFICLIGHTSTATERED = 3,
    TrafficLightSM_StateId_TRAFFICLIGHTSTATEREDYELLOW = 4,
    TrafficLightSM_StateId_TRAFFICLIGHTYELLOW = 5
} TrafficLightSM_StateId;

enum
{
    TrafficLightSM_StateIdCount = 6
};


// Generated state machine
// forward declaration
typedef struct TrafficLightSM TrafficLightSM;

// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void TrafficLightSM_ctor(TrafficLightSM* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void TrafficLightSM_start(TrafficLightSM* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void TrafficLightSM_dispatch_event(TrafficLightSM* sm, TrafficLightSM_EventId event_id);

// Thread safe.
char const * TrafficLightSM_state_id_to_string(TrafficLightSM_StateId id);

// Thread safe.
char const * TrafficLightSM_event_id_to_string(TrafficLightSM_EventId id);

// Generated state machine
struct TrafficLightSM
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    TrafficLightSM_StateId state_id;
};

